# demo workflow
# 
# original file https://github.com/hashicorp/vagrant/blob/a8ce6783301cd0725514438f9f39c64f1d0cac18/.github/workflows/testing.yml

name: Vagrant Ruby Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - 'bin/**'
      - 'lib/**'
      - 'plugins/**'
      - 'test/**'
      - 'Gemfile'
      - 'templates/**'
      - 'vagrant.gemspec'
      - 'Rakefile'

jobs:
name: Vagrant Ruby Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - 'bin/**'
      - 'lib/**'
      - 'plugins/**'
      - 'test/**'
      - 'Gemfile'
      - 'templates/**'
      - 'vagrant.gemspec'
      - 'Rakefile'

jobs:
  unit-tests-ruby:
    runs-on: ubuntu-24.04
    name: Vagrant unit tests on Ruby 3.2
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3.5.3
      - name: Install dependencies for Ruby setup
        run: |
          sudo apt update
          sudo apt install -y git curl autoconf bison build-essential libssl-dev libyaml-dev libreadline-dev zlib1g-dev
      - name: Install rbenv and Ruby
        run: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(rbenv init - bash)"' >> ~/.bashrc
          source ~/.bashrc
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
          ~/.rbenv/bin/rbenv install 3.2.0
          ~/.rbenv/bin/rbenv global 3.2.0
      - name: Install dependencies
        run: sudo apt -y install libarchive-tools
      - name: Install Bundler
        run: gem install bundler
      - name: Run Tests
        run: bundle exec rake test:unit
name: Vagrant Ruby Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - 'bin/**'
      - 'lib/**'
      - 'plugins/**'
      - 'test/**'
      - 'Gemfile'
      - 'templates/**'
      - 'vagrant.gemspec'
      - 'Rakefile'
